version: '3.8'

services:
  # Define the service for your portfolio application for local testing
  portfolio-app:
    # Tell Docker Compose to build the image from the current directory
    build: .
    # Give the container a friendly name for easy identification
    container_name: portfolio-app-local
    # Always restart the container unless it is explicitly stopped
    restart: unless-stopped
    # Map port 8080 on your local machine to port 80 in the container.
    # This allows you to access the app at http://localhost:8080
    ports:
      - "8080:80"